#
# Wahey, a messed up makefile for building libraries!
#
# $Id: Makefile,v 1.17 2007/06/11 12:45:09 stefano Exp $

include ../Make.config

default:
	$(LIBLINKER) -x$../$(OUTPUT_DIRECTORY)/malloc @malllist

clean:
	$(RM) *.o* *.sym *.map *~ *.err zcc_opt.def *.i 

