# $Id: Makefile,v 1.4 2005/09/07 01:30:34 aralbrec Exp $

lzx:	
	cd spectrum ; $(MAKE) ; cd ..

lz88:
	cd z88 ; $(MAKE) ; cd ..

clean:
	cd z88 ; $(MAKE) clean ; cd ..
	cd spectrum ; $(MAKE) clean ; cd ..
