#
# Wahey, a messed up makefile for building libraries!
#
# $Id: Makefile,v 1.3 2002/10/22 19:15:23 dom Exp $

all:
	@echo "Nowt here, who's gonna write sommat?"


clean:
	$(RM) *.o* *.sym *.map zcc_opt.def
