# $Id: Makefile,v 1.13 2003/09/16 19:00:33 denniz Exp $

lcpc:
	cd cpc ; $(MAKE)

lz88:
	cd z88 ; $(MAKE) z88_fcntl

lzx:	
	cd spectrum ; $(MAKE)
	cd dummy    ; $(MAKE)

lcpm:
	cd cpm ; $(MAKE)

lpps:
	cd sprinter ; $(MAKE)

lzxvgs:
	cd zxvgs; $(MAKE)

lcpcold:
	cd cpc ; $(MAKE)
	cd dummy    ; $(MAKE)

clean:
	cd cpm ; $(MAKE) clean
	cd dummy ; $(MAKE) clean
	cd spectrum ; $(MAKE) clean
	cd sprinter ; $(MAKE) clean
	cd z88 ; $(MAKE) clean
	cd zxvgs ; $(MAKE) clean
	cd cpc ; $(MAKE) clean
