#
# Wahey, a messed up makefile for building libraries!
#
# $Id: Makefile,v 1.12 2007/12/21 08:04:23 stefano Exp $


all: 
	cd x11 ; $(MAKE) ; cd ..

clean:
	$(RM) *.o
	$(RM) 8080/*.o
	$(RM) abc80/*.o
	$(RM) ace/*.o
	$(RM) aquarius/*.o
	$(RM) c128/*.o
	$(RM) cpc/*.o
	$(RM) gray/*.o
	$(RM) gray/ticalc/*.o
	$(RM) gray/cpc/*.o
	$(RM) msx/*.o
	$(RM) mz/*.o
	$(RM) nascom/*.o
	$(RM) oz/*.o
	$(RM) sam/*.o
	$(RM) spectrum/*.o
	$(RM) text/*.o
	$(RM) text6/*.o
	$(RM) ticalc/*.o
	$(RM) vz200/*.o
	$(RM) z88/*.o
	$(RM) zx81/*.o
	$(RM) zx81/hr/*.o
