#
# Wahey, a messed up makefile for building libraries!
#
# $Id: Makefile,v 1.8 2005/09/07 01:30:33 aralbrec Exp $


all: 
	@echo 'All in asm'

clean:
	cd .. ; $(MAKE) gfxdeps ; cd graphics
	$(RM) aquarius/*.o
	$(RM) c128/*.o
	$(RM) cpc/*.o
	$(RM) mz/*.o
	$(RM) nascom/*.o
	$(RM) oz/*.o
	$(RM) gray/ticalc/*.o
