#
# Wahey, a messed up makefile for building libraries!
#
# $Id: Makefile,v 1.7 2003/09/15 22:54:57 denniz Exp $


all: 
	@echo 'All in asm'

clean:
	cd ../ ; ./gfxdeps.sh
	$(RM) aquarius/*.o
	$(RM) c128/*.o
	$(RM) cpc/*.o
	$(RM) mz/*.o
	$(RM) nascom/*.o
	$(RM) oz/*.o
	$(RM) gray/ticalc/*.o
